### ISSUE TITLE
Definição de requisitos funcionais

### ISSUE THREAD

**Issue by pelinsarix** [InteliJR/4images-project#8]

**Comment by pelinsarix** [comment]
Requisitos Funcionais 

segurança 
- 

imagens 
- as imagens podem ser adicionadas
- as imagens podem ser excluídas
- as descrições das imagens podem ser alteradas
- as imagens podem ser compradas
- as imagens podem ser curtidas

usuários 
- o usuário pode fazer login na plataforma
- o usuário pode recuperar a senha de seu login
- o usuário pode comprar uma imagem
- o usuário pode visualizar algumas imagens na página inicial 
- o usuário pode visualizar alguma imagem de perto 
- o usuário pode curtir uma imagem

assinatura 
- as assinaturas podem oferecer diferentes números de downloads
- manipular o tempo entre downloads

admin
- o administrador pode adicionar imagens 
- o administrador pode excluir imagens 
- o administrador pode alterar a descrição das imagens 
- o administrador pode alterar o preço das imagens

**Comment by chagasma** [comment]
### Usuarios
RF1: O sistema deve garantir que o usuário possa abrir solicitações de fotos para o usuário admin

### Admin
RF1: O sistema deve garantir que o admin possa adicionar imagens ao banco de dados
RF2: O sistema deve garantir que o admin possa deletar imagens do banco de dados
RF3: O sistema deve garantir que o admin possa visualizar transações feitas pelos seus usuários clientes

### Imagem
RF1: O sistema deve garantir que as imagens exibidas no frontend não estejam em sua qualidade máxima
RF2: O sistema deve garantir múltiplas opções de downloads de imagens em diferentes qualidades

### Assinatura

### Segurança
RF1: O sistema deve exigir autenticação de todos os usuários antes de conceder acesso a qualquer recurso.
RF2: O sistema deve suportar múltiplos métodos de autenticação, como senhas, autenticação de dois fatores.
RF3: O sistema deve garantir a integridade dos diferentes níveis de acesso entre usuários, tipos de assinantes e admin.
RF4: O sistema deve criptografar todas as informações confidenciais em repouso e em trânsito.
RF5: O sistema deve usar apenas protocolos de comunicação seguros.
RF6: O sistema deve restringir o acesso a informações confidenciais apenas aos usuários autorizados.
RF7: O sistema deve proteger seus dados contra modificações não autorizadas.
RF8: O sistema deve implementar mecanismos para detectar e registrar qualquer alteração nos dados.
RF9: O sistema deve permitir a recuperação de dados em caso de perda ou corrupção.
RF10: O sistema deve ser capaz de prevenir e impedir ataques de injeção de sql.

**Comment by ColettoG** [comment]
## Admin
- O administrador deve ser capaz de inserir fotos na aplicação através de plataforma.
- O administrador deve ser capaz de inserir fotos na aplicação utilizando planilhas.

## Users
- O usuário deve ser capaz de fazer login na aplicação com seu usuário e senha.
- O usuário deve ser capaz de recuperar senha.
- O usuário deve ser capaz de comprar uma imagem com o tamanho de sua escolha.
- O usuário deve ser capaz de fazer o pagamento de forma online de acordo com os padrões de mercado.
- O usuário pode pesquisar por uma imagem.

## Imagens, 
- O sistema deve ser capaz de redimensionar as imagens para a sua visualização no frontend
- A imagem deve ser visualizada com marca d'água

## Assinatura
- O usuário deve ser capaz de contratar uma assinatura mensal.
- O usuário deve ter um limite de imagens a serem baixadas de acordo com seu plano
